"""create_companies_table

Revision ID: 163374e87166
Revises: 076e3a917393
Create Date: 2024-08-27 22:44:51.073357

"""

from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "163374e87166"
down_revision: Union[str, None] = "076e3a917393"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    companies_table = op.create_table(
        "companies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum(
                "PUBLIC", "PRIVATE", "INTERNAL", "CONFIDENTIAL", name="company_mode"
            ),
            nullable=True,
        ),
        sa.Column("rating", sa.Double(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # data seeding
    op.bulk_insert(
        companies_table,
        [
            {
                "id": "3a388e09-7d0e-4460-9c48-698e0211694e",
                "name": "Company 1",
                "description": "Description 1",
                "mode": "PUBLIC",
                "rating": 4.5,
            },
            {
                "id": "3a6d21fd-b1a6-4104-95f7-84223d9f85cd",
                "name": "Company 2",
                "description": "Description 2",
                "mode": "PRIVATE",
                "rating": 3.5,
            },
            {
                "id": "a404b4d4-4096-4ae7-87cb-b3046d5e959f",
                "name": "Company 3",
                "description": "Description 3",
                "mode": "INTERNAL",
                "rating": 4.0,
            },
            {
                "id": "c2b74c81-6536-4dae-9404-3a24212986f0",
                "name": "Company 4",
                "description": "Description 4",
                "mode": "CONFIDENTIAL",
                "rating": 4.8,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE companies")
    op.execute("DROP TYPE IF EXISTS company_mode")
    # ### end Alembic commands ###
