"""add_users_tasks_companies_relationship

Revision ID: 2d4ecd905e19
Revises: 8c4ef4505c22
Create Date: 2024-08-28 16:24:17.669136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2d4ecd905e19"
down_revision: Union[str, None] = "8c4ef4505c22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("assignee_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_tasks_users_assignee_id", "tasks", "users", ["assignee_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_tasks_users_assignee_id", "tasks", type_="foreignkey")
    op.drop_column("tasks", "assignee_id")
    # ### end Alembic commands ###
