"""add_unique_uesrname_email_contrainsts

Revision ID: b2f60caff705
Revises: 2d4ecd905e19
Create Date: 2024-08-30 16:33:45.839467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b2f60caff705"
down_revision: Union[str, None] = "2d4ecd905e19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "users_unique_username_constraint", "users", ["username"]
    )
    op.create_unique_constraint("users_unique_email_constraint", "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_unique_username_constraint", "users", type_="unique")
    op.drop_constraint("users_unique_email_constraint", "users", type_="unique")
    # ### end Alembic commands ###
